# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#
# Reference (https://github.com/kan-bayashi/ParallelWaveGAN/)


###########################################################
#                   DATA SETTING                          #
###########################################################
sampling_rate: 24000
data:
    path: /workspace/data/libritts
    subset:
        train: train-clean-460
        valid: test-clean
        test:  test-clean

###########################################################
#                    STATISTIC SETTING                    #
###########################################################
analyzer: exp/autoencoder/symAD_libritts_24000_hop300/checkpoint-500000steps.pkl
stats: stats/symAD_libritts_24000_hop300_clean.npy
