base_config: symAD_libritts_24000_hop300.yaml
tag: autoencoder/symAD_libritts_24000_hop300_train-clean-460_normalized_9600_no_context_sample15900
data:
    subset:
        train: train-clean-460_normalized
sampling_context_length: 15900
