base_config: symAD_libritts_24000_hop300.yaml
tag: jul20_normalized_9600_real_context15900
data:
    subset:
        train: train-clean-460_normalized
context_length: 15900
sampling_context_length: 15900
